save_dir: "./results/attribute_control/generate/gpt2/sentiment-positive"
seed: 42
---
dataset:
        task: cc-news
---
generator:
        type: "generator"
        name: "gpt2"
        max_length: 128
        max_new_tokens: 63
        decode_strategy: "sample"
---
classifier:
        type: "classifier"
        name: "VictorSanh/roberta-base-finetuned-yelp-polarity"
        max_length: 192
        num_labels: 2
---
trainer:
        method: "attribute_control" 
        epochs: 6
        batch_size: 32
        lr: "2e-5"
        weight_decay: 0.01
        warm_up_epochs: 3
        gradient_accumulation_steps: 4
        max_grad_norm: 1.0
        attribute_label: 1
        gumbel_temp_max: 0.5
        gumbel_temp_min: 0.1

        
        